#!/usr/bin/env python
class SupportedFeatures(object):
    #TODO: test_requires is still using it's own internal SupportedFeatures func
    def __init__(self, driver_name): 
        """ This is just a placeholder for the day when we've identified the
           differences between the major drivers.  At that point, it should 
           set attributes according to the driver's capabilities.
        """
        if driver_name == 'pysqlite2':
            self.explicit_db_create = False
            self.inoperable_closed_connections = False
            self.authentication = False
            self.sane_empty_fetch = False
            self.driver_level_datatypes = False
            self.time_datatype = False
            self.transactional_ddl = False
            #self.callproc = False
        elif driver_name == 'psycopg2':
            self.serial_key_def = 'serial'
        elif driver_name == 'pydb2':
            self.serial_key_def = "int generated by default as identity"

    transactional_ddl = True
    connection_level_exceptions = True
    rollback_defined = True
    call_proc = True
    explicit_db_create = True
    authentication = True
    inoperable_closed_connections = True
    connection_level_exceptions = True
    sane_empty_fetch = True
    driver_level_datatypes = True
    time_datatype = True
    serial_key_def = 'int'
    callproc = True
    
    # Name of stored procedure to convert string->lowercase
    lower_func = 'lower'

dbapi_level = "2.0"
